name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature you'd like.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why would this feature be useful?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered.
